# Generated by Django 6.0.2 on 2026-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
