# Generated by Django 6.0.2 on 2026-02-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_library', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100),
        ),
    ]
