# Generated by Django 6.0.2 on 2026-02-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_library', '0004_genre_alter_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genre_fk',
        ),
    ]
