# Generated by Django 6.0.2 on 2026-02-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_library', '0005_rename_genre_book_genre_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre_fk',
            new_name='genre',
        ),
    ]
